# AUTOGENERATED! DO NOT EDIT! File to edit: ../003_simulation.ipynb.

# %% auto 0
__all__ = ['sequence_to_squiggle']

# %% ../003_simulation.ipynb 2
import scrappy
import numpy as np

# %% ../003_simulation.ipynb 3
def _squiggle_normalized(signals):
    '''
    :param signals:
    :return:
    '''
    normalized_signals = []
    for i in signals:
        dwell = int(np.ceil(i[2]))
        normalized_signals += [i[0]]*dwell

    return normalized_signals


def sequence_to_squiggle(sequence, model='squiggle_r94_rna'):
    '''
    :param sequence:
    :param model:
    :return:
    '''

    signals = scrappy.sequence_to_squiggle(
        sequence,
        model=model,
        rescale=True).data(as_numpy=True, sloika=False)
    return _squiggle_normalized(signals)

