# AUTOGENERATED! DO NOT EDIT! File to edit: ../002_worker.ipynb.

# %% auto 0
__all__ = ['process_worker']

# %% ../002_worker.ipynb 2
from concurrent.futures import ProcessPoolExecutor
from rich.progress import track

# %% ../002_worker.ipynb 3
def process_worker(func, args, n_workers=1,desc=None):
    """
    Process worker
    """
    with ProcessPoolExecutor(n_workers) as executor:
        if None is desc:
            return executor.map(func, args)
        else:
            return list(track(executor.map(func, args), total=len(args), description=desc))
        
